version: '3.5'

services:
  # Retreival Container
  retreival:
    container_name: maaniretreival
    build:
      context: ./../golang
      dockerfile: Dockerfile
    image: maani:latest
    entrypoint: /opt/maani/retreival
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./settings.yml:/opt/maani/settings.yml  # Mount local settings.yml into the container
    networks: 
      - maaninode-network  
  # maaninode Container
  maaninode:
    container_name: maaninode
    build:
      context: .
      dockerfile: Dockerfile
    image: maaninode:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./settings.yml:/opt/maani/settings.yml  # Mount local settings.yml into the container
    networks: 
      - maaninode-network
  # TimescaleDB Database
  db:
    container_name: maaninode-db
    image: timescale/timescaledb:2.9.2-pg14
    env_file:
      - .env.compose
    volumes:
      - nodepostgres:/data/postgres
    ports:
      - "54320:5432"
    restart: unless-stopped 
    networks: 
      - maaninode-network
volumes:
  nodepostgres:
networks:
  maaninode-network:
    driver: bridge